### PR TITLE
Elwalid recover table

### PR DESCRIPTION
**Pull request by ewibrahim**
Proposition for [recover_table(fully_qualified_table, timestamp)](https://github.com/unytics/bigfunctions/issues/14)

### CODE REVIEW

**Comment by unytics** [comment]
Thanks @ewibrahim for the input. 

However, I think this function should be able to work without snapshot enabled using bigquery time travel. 

https://cloud.google.com/bigquery/docs/time-travel#query_data_at_a_point_in_time


```
create or replace my_project.my_dataset.my_table as 
select * from 
my_project.my_dataset.my_table
FOR SYSTEM_TIME AS OF timestamps;
```

should make the job. 
(but adding the correct table options, description, etc)

Maybe we could combine both time travel and snapshot

**Comment by ewibrahim** [comment]
Thank you for your answer,

What do you mean by table options ? should i add optional parameters in the
function ? If yes which ones apart from description would you want ?

**Comment by unytics** [comment]
partition config should be kept for instance as well as any other configuration.

as seen here, ddl to create the table is in information schema:
https://cloud.google.com/bigquery/docs/information-schema-tables#schema

image


maybe we could use it at the same `sytem_time`

**Comment by unytics** [comment]
Thanks @ewibrahim, I'll have a look. 
Could you join [the slack](https://join.slack.com/t/bigfunctions/shared_invite/zt-1gbv491mu-cs03EJbQ1fsHdQMcFN7E1Q) so that it faciliates conversation?

Thansk

**Comment by unytics** [comment]
It seems that for now, it is not possible to use time travel on a deleted table with sql (while it is possible with bq command line).
So I close this pull request that I may re-open the day when it becomes possible.

**Pull request closed without merging**
