### PR TITLE
Implement Frequency-Based Anomaly Detection (FBAD) BigFunction

### PR DESCRIPTION
**Pull request by TFMV**
This PR introduces a new BigFunction named fbad_anomalies that detects anomalies in datasets based on the frequency of values. This function is designed to help identify rare or unusual occurrences in various types of datasets.

### CODE REVIEW

**Comment by TFMV** [comment]
Apologies for the typo in the function name on the first commit.

**Comment by TFMV** [comment]
Due to my mistake, both fdab and fbad were deployed. fdab was a typo and should be removed. Apologies and thank you.

**Comment by unytics** [comment]
Thanks @TFMV for this great function. 

I merged it. 

I liked this function very much.

I appreciated the effort to adapt your style with the one of the repo with CTEs and extended description. 

I nonetheless took the liberty:

- to rename it into `rare_values` to be more explicit than fdab or fbad
- to make the description lighter. 

I deployed the function everywhere. 

[Here](https://unytics.io/bigfunctions/bigfunctions/rare_values/) is the doc.


I also deployed the opposite function: `frequent_values` on the 39 public datasets and kept you as author as it is identical. [There ](https://unytics.io/bigfunctions/bigfunctions/frequent_values/)is the doc.

**Comment by TFMV** [comment]
Thanks so much.

**Pull request merged**
